version: '3.4'
 
services:

  parkingapi:
    image: parkingapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:80"
      - "4000:4000"
    depends_on:
            - postgresql_database
    networks:
     - uhpcompany
 
  postgresql_database:
    image: postgres:latest
    environment:

      - POSTGRES_USER=Test
      - POSTGRES_PASSWORD=Test1234
      - POSTGRES_DB=Test
    ports:
      - "5555:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
     - uhpcompany
     
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
     - uhpcompany
 
volumes:
  database-data:
  pgadmin:


networks:
  uhpcompany:
    driver: bridge